### ISSUE TITLE
Check wording for 'State'

### ISSUE THREAD

**Issue by ajack764** [AMILookup/amilookup.com-infra#5]
Check what the wording is for AMI's that don't have State: available.

Looking for unavailable etc.

**Comment by lordmuffin** [comment]
@ajack764 
So there is very little (nothing) on this topic.  With that being said I did some exploration via the CLI.  "available" is the default/only state for all ami's in the marketplace currently.  I'm thinking that the only reason it would be in a different state is if its pending to become available (still creating) or of its pending deletion (this may or may not be true at all).

So with all this being said we can basically bank on only ever having "available" until we get to V2 and start archiving AMI's.
